//
//  SuffilGenerator.swift
//  SuffixLang
// 
//  Created by Emil Pedersen on 05/11/2022.
//  Copyright © 2022 Emil Pedersen (emil.codes). All rights reserved.
// 
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

import Foundation
import SuffixLang

public class SuffilGenerator {
    var rootBlock: BlockContent
    public var passes: [SuffilPass] = SuffilGenerator.defaultPasses
    public var verbose = false
    
    // output
    /// The diagnostics generated by this type checker
    public internal(set) var diagnostics: [Diagnostic] = []
    /// The functions that were found. Includes named, anonymous and synthesized functions, but not builtins
    public internal(set) var functions: [Function] = []
    
    public var logger = Logger()
    
    public init(rootBlock: BlockContent) {
        self.rootBlock = rootBlock
    }
    
    func checkPasses() {
        if !(passes.first is ClosurePass) {
            print("warning: invalid passes: expected closure resolution to be the first pass")
        }
    }
    
    public func generate() {
        checkPasses()
        if verbose {
            print("Starting build")
        }
        let builtinContext = BuiltinParsingContext.shared
        for binding in builtinContext.bindings {
            logger.log(.globalBindingCreated(binding, nil))
        }
        let rootContext = RootParsingContext(typechecker: self, builtins: builtinContext)
        rootBlock.typecheckContent(context: rootContext)
        for pass in passes {
            guard !diagnostics.contains(where: { $0.severity >= .error }) else {
                print("Skipping remaining passes because of errors")
                break
            }
            if verbose {
                print("Running pass: \(pass)")
            }
            pass.run(typechecker: self)
        }
    }
    
    func prepareSuffilForPrinting() {
        for function in functions {
            function.prepareSuffilForPrinting()
        }
    }
    
    public func getSuffil() -> String {
        prepareSuffilForPrinting()
        return functions.map(\.description).joined(separator: "\n")
    }
}

public extension SuffilGenerator {
    static let defaultPasses: [SuffilPass] = [
        ClosurePass(),
        MovePass(),
        DeadCodePass(),
    ]
    static let lspPasses: [SuffilPass] = [
        ClosurePass(),
    ]
}
