//
//  TypeChecker.swift
//  SuffixLang
// 
//  Created by Emil Pedersen on 05/11/2022.
//  Copyright © 2022 Emil Pedersen (emil.codes). All rights reserved.
// 
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

import Foundation
import SuffixLang

public final class TypeChecker {
    var rootBlock: BlockContent
    public var verbose = false
    
    // output
    /// The diagnostics generated by this type checker
    public internal(set) var diagnostics: [Diagnostic] = []
    
//    public var logger = Logger()
    
    public init(rootBlock: BlockContent) {
        self.rootBlock = rootBlock
    }
    
    public func typecheck() {
        if verbose {
            print("Starting build")
        }
        let builtinContext = BuiltinParsingContext.shared
//        for binding in builtinContext.bindings {
//            logger.log(.globalBindingCreated(binding, nil))
//        }
        let rootContext = RootParsingContext(typechecker: self, builtins: builtinContext)
        rootBlock.typecheckContent(context: rootContext)
    }
}
